# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD

on:
  push:
    branches: 
       - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout source
       uses: actions/checkout@v3
     - name: Login to Docker hub
       run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
     - name: Build Docker image
       run: docker build -t rakesharkitan/testing .
     - name: Publish image to docker hub
       run: docker push rakesharkitan/testing:latest
     - name: Publish nginx image
       run: docker push rakesharkitin/testing:nginx:1.23alpine

  deploy:
     needs: build
     runs-on: aws-ec2
     steps:
       - name: pull image from Docker hub
         run: docker pull rakesharkitan/testing:latest
       - name: pull image from Docker hub
         run: docker rakesharkitin/testing:nginx:1.23alpine
       - name: Delete Old container
         run: docker rm -f angularcontainer
       - name: Run docker container
         run: docker run -d -p 4200:80 --name angularcontainer rakesharkitan/testing
       - name: nginx container
         run : docker run -d -p 80:80 --name nginxcontainer rakesharkitin/testing:nginx:1.23alpine
      


   
